
document.writeln('<!DOCTYPE html>');
document.writeln('');
document.writeln('<html lang="en"><head>');
document.writeln('<meta name="viewport" content="width=device-width, initial-scale=1">');
document.writeln('');
document.writeln('<meta charset="utf-8">');
document.writeln('<scr'+'ipt src="https://bajao.pk/theme/js/jquery-2.1.1.js"></scr'+'ipt>');
document.writeln('</head>');
document.writeln('<style>');
document.writeln('body {');
document.writeln('  margin-left:0;');
document.writeln('  margin-right:0;');
document.writeln('  margin-top: 0;');
document.writeln('  margin-bottom:0;');
document.writeln('  background: black;');
document.writeln('  }');
document.writeln('  ');
document.writeln('.container {');
document.writeln('  position: relative;');
document.writeln('  width: 100%;');
document.writeln('  ');
document.writeln('  overflow: hidden;');
document.writeln('  padding-top: 56.25%;');
document.writeln('}');
document.writeln('');
document.writeln('.responsive-video {');
document.writeln('  position: absolute;');
document.writeln('  top: 0;');
document.writeln('  left: 0;');
document.writeln('  bottom: 0;');
document.writeln('  right: 0;');
document.writeln('  width: 100%;');
document.writeln('  height: 100%;');
document.writeln('  border:0;');
document.writeln('  background:black;');
document.writeln('}');
document.writeln('</style>');
document.writeln('	<style>');
document.writeln('');
document.writeln('	');
document.writeln('	img{margin-top:;');
document.writeln('	height:200;');
document.writeln('	width:200;}');
document.writeln('	</style>');
document.writeln('	');
document.writeln('	');
document.writeln('	');
document.writeln('	');
document.writeln('            <div class="container"> ');
document.writeln('           <video id="X"class="responsive-video" poster="https://i.ibb.co/rddSxMc/coollogo-com-25719448-2.gif"controls preload="auto" autoplay muted >');
document.writeln('               <source src="" type="video/mp4">');
document.writeln('           </video>');
document.writeln('           </div>');
document.writeln('<scr'+'ipt type="text/javascr'+'ipt">');
document.writeln('if(win'+'dow.location.hostname !== \'ali4flix.blogspot.com\') win'+'dow.location.replace(\'about:blank\')');
document.writeln('');
document.writeln('');
document.writeln('</scr'+'ipt>');
document.writeln('');
document.writeln('<style>');
document.writeln('      html {');
document.writeln('        display: none;');
document.writeln('      }');
document.writeln('    </style>');
document.writeln('    <scr'+'ipt>');
document.writeln('');
document.writeln('      if ( win'+'dow.location.hostname === "ali4flix.blogspot.com" /* your domain */) {');
document.writeln('        doc'+'ument.doc'+'umentElement.style.display = "block";');
document.writeln('      }');
document.writeln('    </scr'+'ipt>');
document.writeln(' ');
document.writeln(' ');
document.writeln(' ');
document.writeln(' ');
document.writeln(' ');
document.writeln(' ');
document.writeln(' ');
document.writeln(' ');
document.writeln(' ');
document.writeln('<scr'+'ipt>');
document.writeln('');
document.writeln('   ');
document.writeln('	function callapi(slug){');
document.writeln('');
document.writeln('		$.ajax({');
document.writeln('   	url: \'https://cdn2.mjunoon.tv:9191/v2/embed-player-url\',');
document.writeln('   	type: \'post\',');
document.writeln('   	data: {');
document.writeln('   	    slug:slug');
document.writeln('   	},');
document.writeln('   ');
document.writeln('   success: function(result) {');
document.writeln('   var Y = result.data.live_stream_url.replace(/cdn6|cdn7/g, "cdn5");');
document.writeln('   var Z = Y.replace(/8XM-131/g, "geoent-122");');
document.writeln('   var V = doc'+'ument.getElementById("X");');
document.writeln('   V.src = Z;');
document.writeln(' ');
document.writeln('   }');
document.writeln('   ');
document.writeln('');
document.writeln(' 		});');
document.writeln('		}');
document.writeln('	$(doc'+'ument).ready(function(){        ');
document.writeln('	var urlParams = new URLSearchParams(location.search);        ');
document.writeln('	var slug = urlParams.get(\'slug\');');
document.writeln('	callapi(\'8xm-live\');');
document.writeln('	});');
document.writeln('</scr'+'ipt>');
document.writeln('																		');
document.writeln('               ');
document.writeln('	');
document.writeln('</body></html>');